/* eslint-disable @next/next/no-html-link-for-pages */
"use client";
import { FormEvent, useState } from "react";
import { Brand } from "../brand";
export default function Login(){
 const[mode,setMode]=useState<"login"|"signup">("login");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=new FormData(event.currentTarget);const response=await fetch(`/api/auth/${mode}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:form.get("name"),email:form.get("email"),password:form.get("password")})});const data=await response.json();setBusy(false);if(!response.ok)return setMessage(data.error||"Request failed");if(mode==="login")location.assign("/dashboard");else{setMessage(data.message);window.setTimeout(()=>location.assign("/dashboard"),900)}}
 return <main className="auth-page"><section className="auth-card"><div className="auth-brand"><Brand/></div><h1>{mode==="login"?"Welcome back":"Create your workspace"}</h1><p>Secure access to multimodal models, conversations, usage, and billing.</p><div className="auth-tabs"><button className={mode==="login"?"active":""} onClick={()=>setMode("login")}>Sign in</button><button className={mode==="signup"?"active":""} onClick={()=>setMode("signup")}>Register</button></div><form className="auth-form" onSubmit={submit}>{mode==="signup"&&<label>Full name<input name="name" required minLength={2}/></label>}<label>Email<input type="email" name="email" required autoComplete="email"/></label><label>Password<input type="password" name="password" required minLength={8} autoComplete={mode==="login"?"current-password":"new-password"}/></label><button className="auth-submit" disabled={busy}>{busy?"Please wait…":mode==="login"?"Secure sign in":"Create account"}</button></form>{message&&<div className="auth-message">{message}</div>}<a className="auth-back" href="/">← Return to ZetaZAI</a></section></main>
}
