/* eslint-disable @typescript-eslint/no-explicit-any, @next/next/no-html-link-for-pages */
"use client";
import {useState} from "react";
const plans=[
 {name:"Free",tag:"Explore",usd:0,bdt:0,priceId:"",features:["25 requests every day","6 essential AI models","3 file uploads","7-day conversation history"]},
 {name:"Starter",tag:"Build",usd:3,bdt:300,priceId:"price_starter",features:["500 requests monthly","12 AI models","3 projects and 3 agents","Documents and project tools","30-day history"]},
 {name:"Pro",tag:"Most popular",usd:9,bdt:900,priceId:"price_pro",featured:true,features:["5,000 requests monthly","All 24+ AI models","Unlimited projects and 10 agents","Knowledge, files and API access","Unlimited conversation history"]},
 {name:"Business",tag:"Scale",usd:25,bdt:2500,priceId:"price_business",features:["20,000 pooled requests","5 team seats included","Unlimited specialized agents","Admin, roles and audit logs","Priority support and SLA"]}
];
const methods=[{id:"bkash",name:"bKash",mark:"b",tone:"pink"},{id:"nagad",name:"Nagad",mark:"N",tone:"orange"},{id:"rocket",name:"Rocket",mark:"R",tone:"violet"},{id:"card",name:"Card",mark:"▣",tone:"blue"},{id:"bank",name:"Bank",mark:"৳",tone:"mint"}];
export default function Pricing(){const[yearly,setYearly]=useState(false);const[method,setMethod]=useState("bkash");async function checkout(plan:any){if(!plan.priceId)return location.assign("/login");if(method!=="bkash"&&method!=="card")return alert(`${methods.find(x=>x.id===method)?.name} checkout is prepared for merchant activation. Choose bKash or Card for the configured gateway.`);const provider=method==="card"?"stripe":"bkash";const endpoint=provider==="stripe"?"/api/billing/stripe/checkout":"/api/billing/bkash/create";const amount=yearly?Math.round(plan.bdt*12*.8):plan.bdt;const payload=provider==="stripe"?{priceId:plan.priceId,billing:yearly?"yearly":"monthly"}:{amount,plan:plan.name.toLowerCase()};const response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(response.status===401)return location.assign("/login");if(data.url)location.assign(data.url);else alert(data.error||"Checkout unavailable until merchant credentials are activated")}
return <main className="pricing-page"><div className="pricing-orb orb-one"/><div className="pricing-orb orb-two"/><header className="pricing-header"><a className="auth-brand" href="/">ZetaZeon <b>AI</b></a><nav><a href="/">Workspace</a><a href="/login">Sign in</a></nav></header><section className="pricing-hero"><span>ONE WORKSPACE · 24+ AI MODELS</span><h1>Choose the intelligence<br/><b>your ambition needs.</b></h1><p>Start free, scale when you are ready, and pay globally or locally in Bangladesh.</p><div className="billing-switch"><button className={!yearly?"active":""} onClick={()=>setYearly(false)}>Monthly</button><button className={yearly?"active":""} onClick={()=>setYearly(true)}>Yearly <i>Save 20%</i></button></div></section><section className="plans">{plans.map(plan=>{const usd=yearly?Math.round(plan.usd*12*.8):plan.usd;const bdt=yearly?Math.round(plan.bdt*12*.8):plan.bdt;return <article className={`plan ${plan.featured?"featured":""}`} key={plan.name}>{plan.featured&&<div className="popular">MOST POPULAR</div>}<small>{plan.tag}</small><h2>{plan.name}</h2><p>{plan.name==="Free"?"For trying the workspace":plan.name==="Creator"?"For independent creators":plan.name==="Pro"?"For professionals and builders":"For growing teams"}</p><div className="price">${usd}<small> / {yearly?"year":"month"}</small></div>{bdt>0&&<div className="bdt">or ৳{bdt.toLocaleString()} BDT</div>}<button className="plan-cta" onClick={()=>checkout(plan)}>{plan.name==="Free"?"Start free":"Choose "+plan.name} <span>→</span></button><ul>{plan.features.map(x=><li key={x}>✓ <span>{x}</span></li>)}</ul></article>})}</section><section className="local-pay"><div><small>PAY YOUR WAY</small><h2>Global cards. Local convenience.</h2><p>Select a preferred checkout method. bKash and card routes connect to the secure server gateway; additional local methods are ready for merchant activation.</p></div><div className="payment-methods">{methods.map(x=><button className={`${x.tone} ${method===x.id?"selected":""}`} key={x.id} onClick={()=>setMethod(x.id)}><b>{x.mark}</b><span>{x.name}<small>{x.id==="card"?"Visa · Mastercard":x.id==="bank"?"Local transfer":"Bangladesh"}</small></span><i>{method===x.id?"●":"○"}</i></button>)}</div></section><footer className="pricing-foot"><span>Secure checkout · Cancel anytime · Usage controls included</span><a href="/">← Return to workspace</a></footer></main>}
